title: Per Ragnar
description: perragnar.com – Per Ragnar Edin – Web developer, web designer, graphic designer and photographer newbie

host: 0.0.0.0

baseurl:

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
future: false
show_drafts: false
featured_posts: 5
show_content: true
# paginate: 20
# paginate_path: "/blog/page:num"

excerpt_separator: <!--more-->

gems:
- jekyll-sitemap

sass:
  sass_dir: assets/_scss
  style: compressed

exclude: [node_modules, gulpfile.js]

google_analytics_id: UA-120155-5
