title: Per Ragnar
secondary-title: Webbutvecklare
description: perragnar.com – Per Ragnar Edin – Webbutvecklare, webbdesigner och grafiker

baseurl:

navigation:
  - title: Hem
    url: /
  - title: Blog
    url: /blog/
  - title: Arkiv
    url: /archive/

markdown: kramdown

highlighter: rouge

permalink: /:year/:month/:day/:title/

future: false

show_drafts: false

paginate: 10
paginate_path: "/blog/page:num"

excerpt_separator: <!--more-->

gems: [jekyll-paginate]

sass:
  sass_dir: _scss

exclude: [node_modules, gulpfile.js]

google_analytics_id: UA-120155-7

disqus_shortname: perragnarcom
