title: Per Ragnar Edin
secondary-title: Webbutvecklare

baseurl:

navigation:
  - title: Hem
    url: /
  - title: Blog
    url: /blog/
  - title: Arkiv
    url: /archive/
  #- title: Om
  #  url: /about/

markdown: kramdown

highlighter: rouge

permalink: pretty

paginate: 10
paginate_path: "/blog/page:num"

excerpt_separator: <!--more-->

gems: [jekyll-paginate]

sass:
  sass_dir: _scss

exclude: [node_modules, gulpfile.js]
