title: Per Ragnar
secondary-title: Webbutvecklare
description: perragnar.com – Per Ragnar Edin – Webbutvecklare, webbdesigner och grafiker

host: 0.0.0.0

baseurl:

navigation:
  - title: Hem
    url: /
  - title: Blog
    url: /blog/
  - title: Arkiv
    url: /archive/
  - title: Index
    url: /tags/

markdown: kramdown

highlighter: rouge

permalink: /:year/:month/:day/:title/

future: false

show_drafts: false
show_related_posts: true
show_comments: false
show_poster_in_post_list: true

paginate: 5
paginate_path: "/blog/page:num"

excerpt_separator: <!--more-->

gems:
- jekyll-paginate
- jemoji
- jekyll-sitemap

sass:
  sass_dir: _scss
  style: compressed

exclude: [node_modules, gulpfile.js]

google_analytics_id: UA-120155-5

disqus_shortname: perragnarcom
